services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app/app:ro
      - ./backend/tests:/app/tests:ro
      - ./backend/run.py:/app/run.py:ro
      - ./config.yml:/app/config.yml:ro
    ports:
      - "3500:3500"
    entrypoint:
      - python
      - run.py
