name: Main CI

on:
  push:
  pull_request:

jobs:
  docker_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create user config
      run: cp tests/sample_config.yml config.yml

    - name: Run Tests
      run: make