name: Main CI

on:
  push:
  pull_request:

jobs:
  docker_test:

    runs-on: ubuntu-latest

    env:
      ci_testing: true

    steps:
    - uses: actions/checkout@v3

    - name: Run Tests
      run: make